"""add vacancy owner

Revision ID: 1a82d4d754b6
Revises: c14a8d8e4df3
Create Date: 2026-08-19 21:41:04.369236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a82d4d754b6'
down_revision: Union[str, Sequence[str], None] = 'c14a8d8e4df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'owner_id')
    # ### end Alembic commands ###
