"""add index to vacancies owner_id

Revision ID: 381aae7e53e7
Revises: 03b50eb21633
Create Date: 2026-08-26 18:35:53.786293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381aae7e53e7'
down_revision: Union[str, Sequence[str], None] = '03b50eb21633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vacancies_owner_id'), 'vacancies', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_owner_id'), table_name='vacancies')
    # ### end Alembic commands ###
