"""nullable=False for vacancies.owner_id

Revision ID: c203afba58b2
Revises: 1a82d4d754b6
Create Date: 2026-08-19 21:48:33.176723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c203afba58b2'
down_revision: Union[str, Sequence[str], None] = '1a82d4d754b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
